Algoritmo "semnome"
// Disciplina   : Lógica de Programação
// Professor   : Adriano Leite da Silva 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/06/2020
Var
valor, numero: inteiro


Inicio
numero <- 1
escreva("Digite um valor: ")
leia(valor)

repita
 escreval(valor, " X ", numero, " = ", valor * numero)
 numero <- numero + 1
ate ( numero = 21)


Fimalgoritmo