Algoritmo "semnome"
// Disciplina   : Lógica de Programação
// Professor   : Adriano Leite da Silva 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/06/2020
Var
i, numero: inteiro


Inicio

escreva("Digite o número que você deseja a tabuada: ")
leia(numero)

enquanto (i <= 10) faca

escreval(i * numero)
i <- i + 1

fimenquanto


Fimalgoritmo