Algoritmo "Vars"
// Disciplina   : [Lógica de Programação]
// Professor   : Adriano Leite da Silva
// Descrição   : Variáveis
// Autor(a)    : Arthur Hetem
// Data atual  : 18/05/2020
Var
nome: caracter
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
//Pede nome ao usuário e lê o input
escreva("Escreva o seu nome: ")
leia(nome)

//Retorna Bem-vindo com o nome da variável
escreva("Bem-Vindo(a), " + nome)

Fimalgoritmo